project:
  title: LIBS
  type: website
  output-dir: docs
  preview:
    port: 1313

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  # sidebar: 
  #   style: floating
  #   logo: img/logos/aprendeconalf.png
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Inicio
      - href: espectroscopia-libs.qmd
        text: Introducción a LIBS
      - href: software.qmd
        text: Software
      - href: simulacion-espectros.qmd
        text: Simulación de espectros

bibliography: bibliografia.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly
    df-print: paged
    toc: true

knitr:
  opts_chunk: 
    collapse: true
    echo: false
    # cache: true
    # prompt: false
    # tidy: true
    # comment: "#>"
    message: false
    warning: false
    # dev: "png"
    # dev.args: list(type="cairo")
    # dpi: 300

execute:
  cache: true
  #freeze: auto


